db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda0"), page: 1, title: "Ritem", text: ["Vse kar slišimo v glasbi, se povezuje v določene skupine. Tem skupinam pravimo ritmične skupine.", "Ritmične skupine imajo urejeno zaporedje tonskih trajanj. Ti toni si sledijo v določenih časovnih razmakih oziroma v ritmu."]})
db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda1"), page: 2, title: "Metrum uvod", text: ["Poleg ritma, je v glasbi pomemben tudi takt oz. metrum.", "Metrum dobimo tako, da vse kratke in dolge tone razdelimo v enako dolge časovne skupine ali takte."]})
db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda2"), page: 3, title: "Note", text: ["Nota je znamenje za ton. Različno trajanje tonov označujejo različne oblike. V naših vajah lahko srečamo 3 različne oblike not:", "četrtinka: v četrtinskih taktih predstavlja osnovno dobo. Običajno je to osnovna enota merjenja dolžine.", "osminka: je osnovna doba v osminskih taktih. Predstavlja eno polovico dolžine četrtinke.", "polovinka: Je dvakrat daljša od četrtinke. 1 polovnika torej meri 2 četrtinki."]})
db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda3"), page: 4, title: "Pavze", text: ["Poleg note, lahko v vajah nastopa tudi pavza.", "V primeru pavze se ton ne zaigra, zavzame pa določeno trajanje. V naših vajah imamo dve pavzi: ", "četrtinsko: zavzame enako trajanje kot četrtinka", "osminsko: zavzame enako trajanje kot osminka"]})
db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda4"), page: 5, title: "Osnovni taktovski način", text: ["Poznamo 2 osnovna taktovska načina oz. metra:", "dvodobni: predstavlja enakomerno hojo npr. vojaki kadar korakajo. Stopinje koraka štejemo kot ena-dve, ena-dve, ...", "tridobni: predstavlja neenakomerno hojo ali tek med igro, kadar naši koraki vnaprej niso znani. Naprimer: ko stopimo enkrat levo, ponovimo dva koraka v desno. Stopinje koraka torej štejemo kot: ena-dve-tri, ena-dve-tri"]})
db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda5"), page: 6, title: "Metrum nadaljevanje", text: ["Metrum je enota v glasbi. Posamezen takt se med seboj loči z navpčno črto imenovano taktnica.", "Metrum se zapiše na začetku notnega črtovja z ulomkom. Zgornja številka pomeni število not v taktu, spodnja pa njihovo notno vrednost. Metrim se običajno imenuje taktovski način ali takt.", "Primeri taktov so:", "- 2/4 dvočetrtinski takt: v enem taktu sta 2 četrtinki ali ena polovinka ali 4 osminke", "- 3/4 tričetrtinski take: v enem taktu so 3 četrtinke ali 6 osmink ali 2 polovinki in 1 četrtinka", "- 5/8 5 osminski takt: v enem taktu je 5 osmink ali 2 četrtinki in ena osminka ali 1 polovinka in 1 osminka"]})
db.lectures.insert({_id: ObjectId("57ea0f1d74cfbe90339cdda6"), page: 7, title: "Tempo", text: ["Vendar krajše note, ki pospešijo gibanje ne pomeni da je ritem hitrejši ali počasnejši.", "Hitrost izmenjevanja med toni se imenuje tempo. Tempo je hitrost izvajanja in se običajno meri v sekundah.", "Tempo se označuje nad notnim črtovjem na dva načina: z besedami (hitro, počasi, ...) ali z dobo takta in številom dob na minuto. "]})



db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda0"), text: "Ritem pomeni urejenost tonov v določenem časovnem razmaku?", page: 1, correctAnswer: "Drži", wrongAnswers: ["Ne drži"], mixedAnswers: ["Drži", "Ne drži"]})
db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda1"), text: "Kako bi razdelili 9 not?", page: 2, correctAnswer: "3 note v prvi takt. 3 note v drugi takt in 3 note v tretji takt", wrongAnswers: ["Vseh 9 not v prvi takt", "4 note v prvi takt, 3 note v drugi takt in 2 noti v tretji takt"], mixedAnswers: ["Vseh 9 not v prvi takt", "3 note v prvi takt. 3 note v drugi takt in 3 note v tretji takt", "4 note v prvi takt, 3 note v drugi takt in 2 noti v tretji takt"]})
db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda2"), text: "Koliko osmink predstavljajo 3 polovnike?", page: 3, correctAnswer: "12", wrongAnswers: ["3", "8", "16"], mixedAnswers:["3", "8", "12", "16"]})
db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda3"), text: "Štiri osminke želimo nadomestiti s tremi pavzami. Na koliko načinov lahko to storimo?", page: 4, correctAnswer: "3", wrongAnswers: ["0", "1", "2", "4"], mixedAnswers:["0", "1", "2", "3", "4"]})
db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda4"), text: "Kateri taktovski način uporabimo pri plesanju valčka?", page: 5, correctAnswer: "tridobni", wrongAnswers: ["dvodobni", "tridobni"], mixedAnswers:["dvodobni", "tridobni"]})
db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda5"), text: "Kateri izmed zapisov je pravilen za 7/8 takt?", page: 6, correctAnswer: "1 polovinka 1 četrtinka 1 osminka", wrongAnswers: ["2 polovinki in 2 četrtinki", "8 osmink", "4 četrtinke"], mixedAnswers:["2 polovinki in 2 četrtinki", "8 osmink", "1 polovinka 1 četrtinka 1 osminka", "4 četrtinke"]})
db.quizzes.insert({lecture: ObjectId("57ea0f1d74cfbe90339cdda6"), text: "Koliko četrtink je možno slišati v 5 minutah, če je doba takta osminka in število dob 80?", page: 7, correctAnswer: "400", wrongAnswers: ["200", "150", "230"], mixedAnswers:["200", "150", "400", "230"]})


